trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'df475c0c-4868-49f4-8f0d-d2ee4c4e01d7'
    azureResourceGroup: 'trial'
    kubernetesCluster: 'myakscluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'manifests/deployment.yaml'
