apiVersion: apps/v1
kind: Deployment
metadata:
  name: javatrial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javatrial
  template:
    metadata:
      labels:
        app: javatrial
    spec:
      containers:
      - name: javatrial
        image: javatrial123/javatrial:latest
        ports:
        - containerPort: 8080
